core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.ItemListView.as_view(), name='home'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('order-summary/', views.OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', views.ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('add-coupon/', views.AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', views.remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', views.PaymentView.as_view(), name='payment'),
    path('request-refund/', views.RequestRefundView.as_view(), name='request-refund')
]

core/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'PayPal')
)


"""
required is often used to make the field optional that is the user would no longer be required to enter the data 
into that field and it will still be accepted. By default, each Field class assumes the value is required. 
So, to make it 'not required' you need to set 'required=False'

"It's a form validator"

""" 
class CheckoutForm(forms.Form):
    shipping_address = forms.CharField(required=False)
    shipping_address2 = forms.CharField(required=False)
    shipping_country = CountryField(blank_label='(select country)').formfield(required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        })) #See the comment at the very bottom
    shipping_zip = forms.CharField(required=False)
    

    billing_address = forms.CharField(required=False)
    billing_address2 = forms.CharField(required=False)
    billing_country = CountryField(blank_label='(select country)').formfield(required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    billing_zip = forms.CharField(required=False)


    same_billing_address = forms.BooleanField(required=False)
    set_default_shipping = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)
    set_default_billing = forms.BooleanField(required=False)
    use_default_billing = forms.BooleanField(required=False)

    payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_CHOICES)

"""
Use "blank_label" to set the label for the initial blank choice shown in forms:

country = CountryField(blank_label='(select country)')

This field can also allow multiple selections of countries. The field will always output a list of countries in 
this mode.



CountrySelectWidget:-

A widget is included that can show the flag image after the select box 
(updated with JavaScript when the selection changes).
"""

class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Promo code',
        'aria-label': 'Recipient\'s username',
        'aria-describedby': 'basic-addon2'
    }))



class RefundForm(forms.Form):
    ref_code = forms.CharField()
    message = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 4
    }))
    email = forms.EmailField()



class PaymentForm(forms.Form):
    stripeToken = forms.CharField(required=False)
    save = forms.BooleanField(required=False)
    use_default = forms.BooleanField(required=False)


"""
'attrs' = attributes.
ek kothay bolte gele ukto input field ti ke bivinno styling dewa. ekhane bootstrap class attribute er vetor 
duto attribute value dewa hoyese. attribute joto ichcha dewa jay ebong onnovabew dewa jay. jemon: CouponForm
"""


"""
Whenever you specify a field on a form, Django will use a default widget that is appropriate to the type of data 
that is to be displayed. However, if you want to use a different widget for a field, you can use the widget 
argument on the field definition. For example:

from django import forms

class CommentForm(forms.Form):
    name = forms.CharField()
    url = forms.URLField()
    comment = forms.CharField(widget=forms.Textarea)

This would specify a form with a comment that uses a larger Textarea widget, rather than the default 
TextInput widget.

"""

core/views.py
import stripe
import random
import string
from django.conf import settings
#from django.utils import timezone
from django.contrib import messages
from .models import Item, OrderItem, Order, Address, Payment, Coupon, Refund, UserProfile
from .forms import CheckoutForm, CouponForm, RefundForm, PaymentForm
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, View

stripe.api_key = settings.STRIPE_SECRET_KEY


def create_ref_code():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=20))



def is_valid_form(values):
    valid = True
    for field in values:
        if field == '': #(import string)
            valid = False
    return valid


"""
def home(request):
    queryset = Item.objects.all()
    context = {
        "items": items
    }
    return render(request, 'core/home.html', context)
"""

class ItemListView(ListView):
    model = Item
    template_name = 'core/home.html'
    context_object_name = 'items' 
    """ei line ti use kora hoy karon class based view use korle home template er
       for loop hobe "for items in object_list". ei line ti dile "for item in items" use kora jabe.
       By default, ListView provide the context as object_list."""
    paginate_by = 8

    # Searching items
    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            items = self.model.objects.filter(title__icontains=query)
        else:
            items = self.model.objects.all()
        return items
        


class ItemDetailView(DetailView):
    model = Item
    template_name = 'core/item_detail.html'
    


@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False
    )
    # At first, define the 'order_qs' variable
    order_qs = Order.objects.filter(user=request.user, ordered=False) #'qs' = query set

    if order_qs.exists():
        order = order_qs[0]

        # Check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists(): # jodi user er order e ukto item ti theke thake.
            order_item.quantity += 1
            order_item.save()
            messages.info(request, f'The item "{item.title}" quantity has been updated')
            return redirect('core:order-summary')
        else:
            order.items.add(order_item)  # User er order e ukto item ti ke order item hishebe add koro.
            messages.info(request, f'Hi, {request.user} ! The item "{item.title}" has been added to your cart')
            return redirect('core:order-summary')

    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request, f'Hi, {request.user} ! The item "{item.title}" has been added to your cart')
        return redirect('core:order-summary')

    """In the Add to Cart View function, at first we need the product id or slug to add the product. 
    So, We are just passing the slug as a parameter of the function. Then we are filtering the product 
    using get_object_or_404 method and storing the product in a variable called 'item'.

    After that, we are creating a cart object by using the get_or_create method. This method returns a tuple. 
    If we were to use cart.objects.create() method, then every time a user clicks add to cart, it will create 
    a duplicate object of that product every time.

    So to avoid that, we need to use get_or_create method to check if the user has the same product in his cart, 
    then it will not going to create a new cart object with the same product again, 
    it will just going to increase the quantity of that product."""



@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]

        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            order.items.remove(order_item)
            order_item.delete()
            messages.info(request, f'Hi, {request.user} ! The item "{item.title}" has been removed from your cart')
            return redirect('core:order-summary')
        else:
            messages.info(request, f'Sorry, {request.user} ! The item "{item.title}" was not in your cart')
            return redirect('core:product', slug=slug)

    else:
        messages.info(request, f'Hi, {request.user} ! You do not have an active order')
        return redirect('core:product', slug=slug)



@login_required
def remove_single_item_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]

        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
                messages.info(request, f'The item "{item.title}" quantity has been updated')
                return redirect('core:order-summary')
            else:
                order.items.remove(order_item)
                order_item.delete()
                messages.info(request, f'Hi, {request.user} ! The item "{item.title}" has completely been removed from your cart')
                return redirect('core:order-summary')
        else:
            messages.info(request, f'Sorry, {request.user} ! The item "{item.title}" was not in your cart')
            return redirect('core:product', slug=slug)
            
    else:
        messages.info(request, f'Hi, {request.user} ! You do not have an active order')
        return redirect('core:product', slug=slug)



class OrderSummaryView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': order
            }
            return render(self.request, 'core/order_summary.html', context)

        except ObjectDoesNotExist:
            messages.info(self.request, f'Hi, {self.request.user} ! You do not have an active order')
            return redirect('core:home')


"""
1. The billing address is where to send the bill or request for payment 
and the shipping address is where to send the product.

2. The billing address is the registered address where the company sends bills or bank statements. 
The address can be edited before making a purchase and then change it back after the purchase.
The shipping address is the address to which the buyers want to get an order shipped. 
It varies from country to country and is set by the individual campaign owner.

3. Billing Address, the address related to the card when making payment.
Shipping Address, might be same as billing address if that’s the place 
the buyers wants to get the parcel shipped. Or if the buyer wants to gift 
the parcel to someone else.

4. A billing address is the address you provided to your bank or credit card company. 
A shipping address is where you’d like your order to be sent.
"""
class CheckoutView(View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            form = CheckoutForm()
            context = {
                'form': form,
                'couponform': CouponForm(),
                'order': order,
                'DISPLAY_COUPON_FORM': True
            }
            shipping_address_qs = Address.objects.filter(
                user=self.request.user,
                address_type='S',
                default=True
            )
            if shipping_address_qs.exists():
                context.update({'default_shipping_address': shipping_address_qs[0]})


            billing_address_qs = Address.objects.filter(
                user=self.request.user,
                address_type='B',
                default=True
            )
            if billing_address_qs.exists():
                context.update({'default_billing_address': billing_address_qs[0]})
            return render(self.request, 'core/checkout.html', context)

        except ObjectDoesNotExist:
            messages.info(self.request, f'Hi, {self.request.user} ! You do not have an active order')
            return redirect('core:checkout')


    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)

            if form.is_valid():
                use_default_shipping = form.cleaned_data.get('use_default_shipping')

                if use_default_shipping:
                    print('Using the defualt shipping address')
                    address_qs = Address.objects.filter(
                        user=self.request.user,
                        address_type='S',
                        default=True
                    )
                    if address_qs.exists():
                        shipping_address = address_qs[0]
                        order.shipping_address = shipping_address
                        order.save()

core/templates/core/checkout.html
{% extends "base.html" %}
{% block content %}
<div class="row">
  <div class="col-md-8">
    <div class="card">
      <form method="POST" class="card-body">
          {% csrf_token %}
        <legend>Shipping Address > <span class="text-muted">Checkout Form</span></legend>
        <div class="hideable_shipping_form">
          <div class="md-form mb-5">
            <input type="text" placeholder="1234 Main St" id="shipping_address" name="shipping_address" class="form-control"/>
            <label for="shipping_address">Address</label>
          </div>
          <div class="md-form mb-5">
            <input type="text" placeholder="Apartment or suite" id="shipping_address2" name="shipping_address2" class="form-control"/>
            <label for="shipping_address2">Address 2 (optional)</label>
          </div>
          <div class="row">
            <div class="col-lg-4 col-md-12 mb-4">
              <label for="country">Country</label>
              {{ form.shipping_country }}
              <div class="invalid-feedback">
                Please select a valid country
              </div>
            </div>
            <div class="col-lg-4 col-md-6 mb-4">
              <label for="shipping_zip">Zip</label>
              <input type="text" placeholder="Zip code" id="shipping_zip" name="shipping_zip" class="form-control"/>
              <div class="invalid-feedback">
                Zip code required
              </div>
            </div>
          </div>
          <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" name="same_billing_address" id="same_billing_address">
            <label class="custom-control-label" for="same_billing_address">Billing address is the same as my shipping address</label>
          </div>
          <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" name="set_default_shipping" id="set_default_shipping">
            <label class="custom-control-label" for="set_default_shipping">Save as default shipping address</label>
          </div>
        </div>
        {% if default_shipping_address %}
        <div class="custom-control custom-checkbox">
          <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping">
          <label class="custom-control-label" for="use_default_shipping">Use default shipping address: {{ default_shipping_address.street_address|truncatechars:10 }}</label>
        </div>
        {% endif %}
        <hr>
        <br>

        <legend>Billing Address</legend>
        <div class="hideable_billing_form">
          <div class="md-form mb-5">
            <input type="text" placeholder="1234 Main St" id="billing_address" name="billing_address" class="form-control"/>
            <label for="billing_address">Address</label>
          </div>
          <div class="md-form mb-5">
            <input type="text" placeholder="Apartment or suite" id="billing_address2" name="billing_address2" class="form-control"/>
            <label for="billing_address2">Address 2 (optional)</label>
          </div>
          <div class="row">
            <div class="col-lg-4 col-md-12 mb-4">
              <label for="country">Country</label>
              {{ form.billing_country }}
              <div class="invalid-feedback">
                Please select a valid country.
              </div>
            </div>
            <div class="col-lg-4 col-md-6 mb-4">
              <label for="billing_zip">Zip</label>
              <input type="text" placeholder="Zip code" id="billing_zip" name="billing_zip" class="form-control"/>
              <div class="invalid-feedback">
                Zip code required.
              </div>
            </div>
          </div>
          <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" name="set_default_billing" id="set_default_billing">
            <label class="custom-control-label" for="set_default_billing">Save as default billing address</label>
          </div>
        </div>
        {% if default_billing_address %}
        <div class="custom-control custom-checkbox">
          <input type="checkbox" class="custom-control-input" name="use_default_billing" id="use_default_billing">
          <label class="custom-control-label" for="use_default_billing">Use default billing address: {{ default_billing_address.street_address|truncatechars:10 }}</label>
        </div>
        {% endif %}
        <hr>
        <br>

        <legend>Payment Option</legend>
        <div class="d-block my-3">
          {% for value, name in form.fields.payment_option.choices %}
          <div class="custom-control custom-radio">
            <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
            <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
          </div>
          {% endfor %}
        </div>
        <hr class="mb-4">
        <button class="btn btn-success btn-lg btn-block" type="submit">Continue To Checkout</button>
      </form>
    </div>
  </div>

  <div class="col-md-4 mb-4">

    {% include "core/order_snippet.html" %}

  </div>
</div>
<div style="width: 100%; height: 50px; "></div>
{% endblock content %}

core/templates/core/home.html
{% extends "base.html" %}
{% block extra_head %}
  <style>

    i {
      color: white;
    }

    i:hover {
      color: red;
    }

    .site-header {
      margin-bottom: 90px;
    }

    .site-header .navbar-expand-md {
      height: 85px;
      background: black;
    }

    .site-header .navbar-brand {
      padding: 7px 7px;
      color: chartreuse;
      font-size: 25px;
      font-style: italic;
    }

    .site-header .navbar-brand:hover {
      background: green;
      color: white;
    }

    .site-header .navbar-nav .nav-link {
      color: yellow;
      font-weight: bold;
    }

    .site-header .navbar-nav .nav-link:hover {
      color: red;
    }

    .badge-danger {
      color: white;
      background-color: red;
    }

    .btn-primary {
      color: white;
      background: green;
      border: 3px solid black;
    }

    .btn-primary:hover {
      color: red;
      background: black;
      border: 3px solid black;
    }

    .search {
        margin-top: 12px; 
        margin-right: 120px;
      }

    .cart {
      margin-right: 150px;
    }

    .card {
      background: #eee8ae;
    }

    .card-img-top {
      width: 100%;
      height:400px;
    }

    .fa {
      padding: 14px;
      font-size: 17px;
      width: 45px;
      text-align: center;
      text-decoration: none;
      border-radius: 50%;
    }

    .fa-facebook {
      background: #3B5998;
      color:white;
    }

    .fa-twitter {
      background: #55ACEE;
      color: white;
      margin-left: 2px;
    }

    .footer-section {
      margin-bottom: 0px;
      width: 100%;
      padding: 50px;
      background: black;
      text-align: center;
      color: white;
      font-style: italic;
    }

  </style>
{% endblock %}


  {% block content %}
      <div class="mb-4">
        <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="/media/slider-1.jpg" class="d-block w-100" height="500">
              </div>
              <div class="carousel-item">
                <img src="/media/slider-2.jpg" class="d-block w-100" height="500">
              </div>
              <div class="carousel-item">
                <img src="/media/slider-3.jpg" class="d-block w-100" height="500">
              </div>
              <div class="carousel-item">
                <img src="/media/slider-4.jpg" class="d-block w-100" height="500">
              </div>
              <div class="carousel-item">
                <img src="/media/slider-5.jpg" class="d-block w-100" height="500">
              </div>
              <div class="carousel-item">
                <img src="/media/slider-6.jpg" class="d-block w-100" height="500">
              </div>
              <div class="carousel-item">
                <img src="/media/slider-7.jpg" class="d-block w-100" height="500">
              </div>
              <div class="carousel-item">
                <img src="/media/slider-8.jpg" class="d-block w-100" height="500">
              </div>
          </div>
      </div>
    </div>

        <div class="row">
          {% for item in items %}
          <div class="col-md-6 mb-3">
            <div class="card">
                <img src="/media/{{ item.image }}" class="card-img-top mb-2">
              <div class="card-body text-center">
                <h6><em>{{ item.category }}</em></h6>    
                  <h5 class="font-weight-bold">
                    <strong>
                      <a href="{{ item.get_absolute_url }}" style="text-decoration: none">{{ item.title }}
                        <span class="badge badge-pill badge-danger">NEW</span>
                      </a>
                    </strong>
                  </h5>               
                    <h4 class="font-weight-bold">
                      <strong>$
                        {% if item.discount_price %}
                            {{ item.discount_price }}
                        {% else %}
                            {{ item.price }}
                        {% endif %}
                      </strong>
                  </h4>
              </div>
            </div>
          </div>
          {% endfor %}
      </div>
  {% endblock content %}
  

core/templates/core/item_detail.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-7 mb-5">
      <img src="/media/{{ object.image }}" width="100%" height="513px">
    </div>
    
      <div class="col-md-5">
          <div class="mb-3">
            <span class="badge badge-dark">{{ object.title }}</span>
          </div>
          <p class="lead">
            {% if object.discount_price %}
              <span class="mr-1">
                <del>${{ object.price }}</del>
              </span>
              <span>${{ object.discount_price }}</span>
            {% else %}
              <span>${{ object.price }}</span>
            {% endif %}
          </p>
            <p class="lead font-weight-bold">Description</p>
              <p class="text-justify"><em>{{ object.description }}</em></p>
                <a href="{{ object.get_add_to_cart_url }}" class="btn btn-success font-weight-bold">
                    ADD TO CART
                  <i class="fa fa-shopping-cart ml-1"></i>
                </a>

                <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger font-weight-bold">
                    REMOVE FROM CART
                  <i class="fa fa-trash ml-1"></i>
                </a>
          </div>

          <div>    
          <hr>
            <div class="row justify-content-center">
              <div class="col-md-6 text-center">
                <h3 class="my-4">Additional Information</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit voluptates, quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>
              </div>
            </div>
        </div>

      </div>
    </div>
{% endblock content %}

core/templates/core/order_snippet.html
<div style="width:100%; background: navy; padding: 1px;">
    <h4 class="d-flex justify-content-between">
        <span class="text-warning ml-1 mt-1">Your cart</span>
        <span class="badge badge-pill badge-danger mr-1 mt-2">{{ order.items.count }}</span>
    </h4>
</div>

<ul class="list-group">

    {% for order_item in order.items.all %}
        <li class="list-group-item d-flex">
            <div class="text-justify">
                <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
                <small class="text-muted">{{ order_item.item.description}}</small>
            </div>
            <span class="text-muted">${{ order_item.get_final_price }}</span>
        </li>
    {% endfor %}

            {% if order.coupon %}
                <li class="list-group-item d-flex justify-content-between bg-light">
                    <div class="text-success">
                    <h6 class="my-0">Promo code</h6>
                    <small>{{ order.coupon.code }}</small>
                    </div>
                    <span class="text-success">-${{ order.coupon.amount }}</span>
                </li>
            {% endif %}

        <li class="list-group-item d-flex justify-content-between">
            <h6><span>Total (USD)</span></h6>
            <strong>${{ order.get_total }}</strong>
        </li>
</ul>

{% if DISPLAY_COUPON_FORM %}
<form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
    {% csrf_token %}
    <div class="input-group">
        {{ couponform.code }}
        <div class="input-group-append">
            <button class="btn btn-secondary" type="submit">Redeem</button>
        </div>
    </div>
</form>
{% endif %}

core/templates/core/order_summary.html
{% extends "base.html" %}
{% block content %}
<h2 style="color: blue; text-align: center; font-weight: bold; font-style: italic; margin-bottom: 1px;">Your Cart</h2>
<table class="table table-bordered table-hover table-dark">

    <thead>
        <tr>
            <th>#</th>
            <th>Item</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total Item Price</th>
        </tr>
    </thead>

    <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th>{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>${{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fa fa-minus mr-2 text-danger"></i></a>
                    {{ order_item.quantity }}
                <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fa fa-plus ml-2 text-success"></i></a>
            </td>
            <td>
                {% if order_item.item.discount_price %}
                    ${{ order_item.get_total_discount_item_price }}
                    <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
                {% else %}
                    ${{ order_item.get_total_item_price }}
                {% endif %}
                <a href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                    <i class="fa fa-trash float-right text-danger"></i>
                </a>
            </td>
        </tr>
            {% empty %}
            <tr>
                <td class="text-center text-danger font-weight-bold" colspan="5">Your cart is empty</td>
            </tr>
            <tr>
                <td class="text-center" colspan="5">
                    <a class="btn btn-success" href="{% url 'core:home' %}">Go shopping</a>
                </td>
            </tr>
        {% endfor %}
        
                {% if object.coupon %}
                    <tr>
                        <td colspan="4"><b>Coupon</b></td>
                        <td><b>-${{ object.coupon.amount }}</b></td>
                    </tr>
                {% endif %}

                {% if object.get_total %}
                    <tr>
                        <td colspan="4"><b>Order Total</b></td>
                        <td><b>${{ object.get_total }}</b></td>
                    </tr>
                    <tr>
                        <td class="text-center" colspan="5">
                            <a class="btn btn-success mr-1" href="{% url 'core:checkout' %}">Proceed to checkout</a>
                            <a class="btn btn-warning" href="{% url 'core:home' %}">Continue shopping</a>
                        </td>
                    </tr>
                {% endif %}
    </tbody>
</table>
<div style="width: 100%; height: 50px;"></div>
{% endblock content %}

core/templates/core/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
 <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Request Refund</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-success" type="submit">Submit</button>
        </div>
    </form>
</div>
<div style="width: 100%; height: 200px; "></div>
{% endblock content %}