core/urls.py
from django.urls import path
from . import views

app_name = 'core'
urlpatterns = [
    path('', views.ItemListView.as_view(), name='home'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('order-summary/', views.OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', views.ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
    path('add-coupon/', views.AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', views.remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', views.PaymentView.as_view(), name='payment'),
    path('request-refund/', views.RequestRefundView.as_view(), name='request-refund')
]

templates/base.html
<!DOCTYPE html>
<html>
<head>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->                                              
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  <!-- Social Share Icon Link -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  {% block extra_head %} {% endblock extra_head %}

  {% load cart_template_tags %}

  {% if title %}
    <title>Ecommerce - {{ title }}</title>
  {% else %}
    <title>Ecommerce</title>
  {% endif %}

  <style>

      body {
        background: #eee;
      }

      .site-header {
          margin-bottom: 95px;
      }

      .site-header .navbar-expand-md {
          height: 85px;
          background: black;
      }

      .site-header .navbar-brand {
          padding: 7px 7px;
          color: chartreuse;
          font-size: 25px;
          font-style: italic;
      }

      .site-header .navbar-brand:hover {
          background: green;
          color: white;
      }

      .site-header .navbar-nav .nav-link {
          color: yellow;
          font-weight: bold;
      }

      .site-header .navbar-nav .nav-link:hover {
          color: red;
      }

      .text-danger {
          color: red!important;
      }

      .text-success {
          color: green!important;
      }

      .btn-success {
        background: green;
        color: white;
      }

      .btn-danger {
        background: red;
        color: white;
      }

      .btn-outline-success {
        color: green;
      }

      .btn-outline-success:hover {
        background: green;
      }

      .badge-danger {
        color: white;
        background-color: red;
      }

      .content-section {
          background: #ffffff; 
          padding: 10px 20px;
          border: 1px solid gray;
          border-radius: 3px;
          margin-bottom: 20px;
      }

      legend {
          color: black; 
          text-align: center; 
          font-weight: bold; 
          font-size: 27px; 
          font-style: italic;
      }


      .search {
          margin-top: 12px; 
          margin-right: 120px;
      }

      .cart {
          margin-right: 150px;
      }

      .fa {
          padding: 14px;
          font-size: 17px;
          width: 45px;
          text-align: center;
          text-decoration: none;
          border-radius: 50%;
      }

      .fa-facebook {
          background: #3B5998;
          color:white;
      }

      .fa-twitter {
          background: #55ACEE;
          color: white;
          margin-left: 2px;
      }

      .footer-section {
          margin-bottom: 0px;
          width: 100%;
          padding: 50px;
          background: maroon;
          text-align: center;
          color: white;
          font-style: italic;
      }

  </style> 
</head>

<!-- Navbar Left Side -->                                                                             
<header class="site-header">
  <nav class="navbar navbar-expand-md fixed-top">
    <div class="container">
      <a class="navbar-brand mr-4 mb-2" href="{% url 'core:home' %}">Ecommerce Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto"></div>

    <!-- Navbar Right Side -->
      <div class="navbar-nav">
        {% if request.user.is_authenticated %}
          <div class="search">
            <form class="form-inline mr-4" method="GET">
                <input class="form-control mr-sm-1" name="q" type="search" placeholder="Search Products...." aria-label="Search" value="{{ request.GET.q }}">
                 <input type="submit" value="Search" class="btn btn-outline-warning btn-md my-0 ml-sm-0">
              </form>
          </div>

            <div class="cart">
              <a class="nav-item nav-link font-weight-bold text-white" 
                href="{% url 'core:order-summary' %}"><i class="fa fa-shopping-cart"></i><span class="badge badge-primary">{{ request.user|cart_item_count }}</span> Cart
              </a>
            </div>
              <a class="nav-item nav-link mt-2" href="{% url 'core:checkout' %}">Checkout</a>
              <a class="nav-item nav-link mt-2" href="{% url 'logout' %}">Logout</a>
        {%else %}                                                                                
              <a class=" btn btn-outline-warning btn-lg" href="{% url 'login' %}">Sign In</a>
              <a class=" btn btn-outline-primary btn-lg ml-2" href="{% url 'register' %}">Sign Up</a>
        {% endif %}
        </div>
      </div>
    </div>
  </nav>
</header>


<body>

 <div class="container">
  <div class="row">
    <div class="col-md-12">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endfor %}
      {% endif %}

  {% block content %} {% endblock content %}

  {% block extra_scripts %} {% endblock extra_scripts %}

    <div class="text-center">
        {% if is_paginated %} 
            {% if page_obj.has_previous %}
              <a class="btn btn-primary mt-5" href="?page=1">First</a>
              <a class="btn btn-primary mt-5" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}
              {% for num in page_obj.paginator.page_range %}
                  {% if page_obj.number == num %}
                      <a class="btn btn-primary mt-5" href="?page={{ num }}">{{ num }}</a>
                  {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                      <a class="btn btn-primary mt-5" href="?page={{ num }}">{{ num }}</a>
                  {% endif %}
              {% endfor %}
                {% if page_obj.has_next %}                                                  
                  <a class="btn btn-primary mt-5" href="?page={{ page_obj.next_page_number }}">Next</a>
                  <a class="btn btn-primary mt-5" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                {% endif %}
        {% endif %}
      </div>
    </div>

  {% block sidebar %} {% endblock sidebar %}

    </div>
</div>

<div style="width: 100%; height: 150px; "></div>

<footer class="footer-section">
    <p class="text-center">&copy;   
      <!-- Dynamic Year -->
  <script type="text/javascript">
      document.write(new Date().getFullYear());
  </script>
      LocalHost.com, All Rights Reserved
    </p>
        <a href="https://facebook.com/arafathossain2229" class="fa fa-facebook"></a>
        <a href="https://twitter.com/Arafat_3449" class="fa fa-twitter"></a>
</footer>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
</html>